services:
  postgres:
    image: postgres:latest
    container_name: ecomm-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerceInt
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data  <-- supprime/commenter pour Windows

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
